apiVersion: apps/v1
kind: Deployment
metadata:
  name: members-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: members-service
  template:
    metadata:
      labels:
        app: members-service
    spec:
      containers:
      - name: members-service
        image: ethanhaller5/members-service:1.0.3
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            cpu: "20m"
            memory: "128Mi"
          limits:
            cpu: "75m"
            memory: "160Mi"