apiVersion: apps/v1
kind: Deployment
metadata:
  name: members-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: members-service
  template:
    metadata:
      labels:
        app: members-service
    spec:
      containers:
      - name: members-service
        image: ethanhaller5/members-service:1.0.3
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
            cpu: "50m"
